In [1]:
element = 'oxygen'
print ('first three characters:', element [0:3])
print ('last three characters:', element [3:6])

first three characters: oxy
last three characters: gen


In [2]:
print (element[:4])

oxyg


In [3]:
print (element[4:])

en


In [4]:
print (element [:])

oxygen


In [5]:
#this gives the last letter
print (element [-1])

n


In [6]:
#this gives the second to last letter
print (element [-2])

e


In [7]:
#this skips the first letter and gives everything up to the last letter
print (element [1:-1])

xyge


In [8]:
print (element [3:3])

In [1]:
#if data holds our array of patient data, the following command would output
#an empty array because the command is saying to start and end at the same row/column

In [2]:
#if data holds our array of patient data, the following command would output
#0 rows and all the columns

In [20]:
import numpy

A = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print ('A= ')
print(A)

B = numpy.hstack ([A,A])
print ('B= ')
print(B)

C = numpy.vstack([A,A])
print ('C= ')
print(C)

A= 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B= 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C= 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
element = A
print (element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
D = element [ :,-1]
print ('D= ')
print (element [ :,-1])

D= 
[3 6 9]


In [36]:
E = element [ :,0]
print ('E= ')
print (element [ :,0])

E= 
[1 4 7]


In [37]:
F = numpy.vstack([E,D])
print ('F= ')
print (F)

F= 
[[1 4 7]
 [3 6 9]]


In [38]:
npdiff = numpy.array([ 0, 2, 5, 9, 14])

In [39]:
#it would make sense to use this function along the x-axis/rows
#doing so, we would calculate changes in inflammation of one individual
numpy.diff(npdiff)

array([2, 3, 4, 5])

In [44]:
#an individual data file with 60 rows and 40 columns
#the shape of the array would be (60,39) because the difference function takes away one column in order to calculate difference

In [45]:
#you find the largest change in inflammation for each patient by
#first find all the differences using numpy.diff()
#then you can use numpy.max() to find the biggest difference in inflammation for each patient
#if the change is an increase or decrease, the absolute value of the difference must be taken